/**
 * Trip Auto-Detection Service (Feature 2)
 * Automatically clusters photos into trips based on spatial distance and chronological gaps.
 */

import { storageService } from './storageService.js';
import { CONFIG } from '../config.js';

class TripDetectionService {
  /**
   * Calculate Haversine distance between two coordinates in kilometers
   */
  calculateDistance(lat1, lon1, lat2, lon2) {
    if (lat1 == null || lon1 == null || lat2 == null || lon2 == null) return 0;
    const R = 6371; // Earth's radius in km
    const dLat = (lat2 - lat1) * (Math.PI / 180);
    const dLon = (lon2 - lon1) * (Math.PI / 180);
    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(lat1 * (Math.PI / 180)) * Math.cos(lat2 * (Math.PI / 180)) *
      Math.sin(dLon / 2) * Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    return R * c;
  }

  /**
   * Infer home location reference point (mode cluster of coordinates)
   * or retrieve user-set home coords from settings
   */
  inferHomeLocation(photos) {
    const savedHome = localStorage.getItem(CONFIG.STORAGE_KEYS.HOME_LOCATION);
    if (savedHome) {
      try {
        const parsed = JSON.parse(savedHome);
        if (parsed.lat != null && parsed.lng != null) return parsed;
      } catch (e) {
        console.warn('Invalid saved home location:', e);
      }
    }

    if (!photos || photos.length === 0) {
      return { lat: 13.0827, lng: 80.2707, name: 'Chennai' }; // Default fallback
    }

    // Cluster by rounded coordinates (0.1 degree ~ 11km)
    const clusterCounts = {};
    photos.forEach(p => {
      if (p.latitude != null && p.longitude != null) {
        const key = `${p.latitude.toFixed(1)},${p.longitude.toFixed(1)}`;
        if (!clusterCounts[key]) {
          clusterCounts[key] = { count: 0, lat: p.latitude, lng: p.longitude, name: p.city || p.locationName };
        }
        clusterCounts[key].count++;
      }
    });

    let maxCluster = null;
    let maxCount = -1;
    Object.values(clusterCounts).forEach(c => {
      if (c.count > maxCount) {
        maxCount = c.count;
        maxCluster = c;
      }
    });

    return maxCluster ? { lat: maxCluster.lat, lng: maxCluster.lng, name: maxCluster.name } : { lat: 13.0827, lng: 80.2707, name: 'Chennai' };
  }

  /**
   * Run Trip Auto-Detection Algorithm across all library photos
   * @param {boolean} [forceRescan=false]
   * @returns {Promise<Array>} List of trips
   */
  async detectTrips(forceRescan = false) {
    const allMedia = await storageService.getAllMedia();
    const existingTrips = await storageService.getAllTrips();

    // Preserve manually edited or created trips (autoGenerated === false)
    const manualTrips = existingTrips.filter(t => t.autoGenerated === false);
    const manualPhotoIds = new Set(manualTrips.flatMap(t => t.photoIds || []));

    // Filter available photos with GPS + dateTaken that are not locked in manual trips
    const geotagged = allMedia
      .filter(m => m.latitude != null && m.longitude != null && m.dateTaken && !manualPhotoIds.has(m.id))
      .sort((a, b) => new Date(a.dateTaken).getTime() - new Date(b.dateTaken).getTime());

    if (geotagged.length === 0) {
      return manualTrips;
    }

    const home = this.inferHomeLocation(geotagged);
    const thresholdKm = parseFloat(localStorage.getItem(CONFIG.STORAGE_KEYS.TRIP_DISTANCE_THRESHOLD)) || 35; // km from home
    const maxGapHours = 48; // max gap between trip photos
    const minPhotosPerTrip = 2; // threshold for a trip (default 2 to catch rich weekend getaways)

    const detected = [];
    let currentTripPhotos = [];

    for (let i = 0; i < geotagged.length; i++) {
      const photo = geotagged[i];
      const distFromHome = this.calculateDistance(home.lat, home.lng, photo.latitude, photo.longitude);
      const isAwayFromHome = distFromHome > thresholdKm;

      if (currentTripPhotos.length === 0) {
        if (isAwayFromHome) {
          currentTripPhotos.push(photo);
        }
      } else {
        const prevPhoto = currentTripPhotos[currentTripPhotos.length - 1];
        const timeGapHours = (new Date(photo.dateTaken).getTime() - new Date(prevPhoto.dateTaken).getTime()) / (1000 * 60 * 60);
        const distFromPrev = this.calculateDistance(prevPhoto.latitude, prevPhoto.longitude, photo.latitude, photo.longitude);

        if (isAwayFromHome && timeGapHours <= maxGapHours) {
          currentTripPhotos.push(photo);
        } else {
          // Check if current cluster qualifies as a trip
          if (currentTripPhotos.length >= minPhotosPerTrip) {
            detected.push(this.formatTripRecord(currentTripPhotos));
          }
          currentTripPhotos = [];
          if (isAwayFromHome) {
            currentTripPhotos.push(photo);
          }
        }
      }
    }

    // Process trailing trip
    if (currentTripPhotos.length >= minPhotosPerTrip) {
      detected.push(this.formatTripRecord(currentTripPhotos));
    }

    // If no distinct >50km away trips were found because all photos are within a region,
    // cluster by major distinct destinations (>25km clusters)
    if (detected.length === 0 && geotagged.length >= 3) {
      const fallbackTrips = this.clusterFallbackTrips(geotagged, minPhotosPerTrip);
      detected.push(...fallbackTrips);
    }

    // Save newly generated trips into IndexedDB
    for (const trip of detected) {
      await storageService.saveTrip(trip);
    }

    // Combine manual trips + detected trips
    const allTrips = [...manualTrips, ...detected];
    allTrips.sort((a, b) => new Date(b.startDate).getTime() - new Date(a.startDate).getTime());
    return allTrips;
  }

  /**
   * Secondary clusterer when all photos are in local/travel destination
   */
  clusterFallbackTrips(photos, minCount) {
    const trips = [];
    const locationGroups = {};

    photos.forEach(p => {
      const locKey = p.city || (p.locationName ? p.locationName.split(',')[0].trim() : 'Destinations');
      if (!locationGroups[locKey]) locationGroups[locKey] = [];
      locationGroups[locKey].push(p);
    });

    Object.entries(locationGroups).forEach(([loc, grp]) => {
      if (grp.length >= minCount) {
        trips.push(this.formatTripRecord(grp, loc));
      }
    });

    return trips;
  }

  /**
   * Format a cluster of photos into a Trip record
   */
  formatTripRecord(photos, nameOverride = null) {
    const photoIds = photos.map(p => p.id);
    const startDate = photos[0].dateTaken;
    const endDate = photos[photos.length - 1].dateTaken;

    // Centroid calculation
    let sumLat = 0;
    let sumLng = 0;
    const locCounts = {};

    photos.forEach(p => {
      sumLat += p.latitude;
      sumLng += p.longitude;
      const name = p.city || (p.locationName ? p.locationName.split(',')[0].trim() : 'Place');
      locCounts[name] = (locCounts[name] || 0) + 1;
    });

    const centroid = {
      lat: sumLat / photos.length,
      lng: sumLng / photos.length
    };

    const sortedLocs = Object.entries(locCounts).sort((a, b) => b[1] - a[1]);
    const dominantLoc = sortedLocs[0] ? sortedLocs[0][0] : 'Explore Journey';
    const distinctLocs = sortedLocs.map(([l]) => l);

    // Auto-generate name: e.g. "Ooty & Nilgiris, May 2024"
    const startD = new Date(startDate);
    const monthYearStr = startD.toLocaleDateString('en-US', { month: 'short', year: 'numeric' });

    let tripName = nameOverride;
    if (!tripName) {
      if (distinctLocs.length > 1) {
        tripName = `${dominantLoc} & ${distinctLocs.length - 1} more, ${monthYearStr}`;
      } else {
        tripName = `${dominantLoc}, ${monthYearStr}`;
      }
    }

    return {
      id: `trip_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`,
      name: tripName,
      startDate: new Date(startDate).toISOString(),
      endDate: new Date(endDate).toISOString(),
      photoIds: photoIds,
      centroid: centroid,
      locations: distinctLocs,
      coverPhotoId: photos[0].id,
      autoGenerated: true
    };
  }
}

export const tripDetectionService = new TripDetectionService();
